export const schools = [
  "Admiralty Sec",
  "Ahmad Ibrahim Sec",
  "Anderson Serangoon JC",
  "Anderson Sec",
  "Anglican High Sch",
  "Anglo-Chinese (Barker Road)",
  "Anglo-Chinese (Independent)",
  "Anglo-Chinese JC",
  "Ang Mo Kio Sec",
  "Assumption English Sch",
  "Bartley Sec",
  "Beatty Sec",
  "Bedok Green Sec",
  "Bedok South Sec",
  "Bedok View Sec",
  "Bendemeer Sec",
  "Boon Lay Sec",
  "Bowen Sec",
  "Broadrick Sec",
  "Bukit Batok Sec",
  "Bukit Merah Sec",
  "Bukit Panjang Govt High",
  "Bukit View Sec",
  "Canberra Sec",
  "Catholic High Sch",
  "Catholic JC",
  "Cedar Girls' Sec",
  "CHIJ Katong Convent Sec",
  "CHIJ Sec",
  "CHIJ St. Joseph's Convent",
  "CHIJ St. Nicholas Girls'",
  "CHIJ St. Theresa's Convent",
  "Changkat Changi Sec",
  "Choa Chu Kang Sec",
  "Christ Church Sec",
  "Chung Cheng High (Main)",
  "Chung Cheng High (Yishun)",
  "Clementi Town Sec",
  "Commonwealth Sec",
  "Compassvale Sec",
  "Crescent Girls' Sch",
  "Damai Sec",
  "Deyi Sec",
  "Dunearn Sec",
  "Dunman High Sch",
  "Dunman Sec",
  "East Spring Sec",
  "Edgefield Sec",
  "Eunoia JC",
  "Evergreen Sec",
  "Fairfield Methodist Sec",
  "Fuchun Sec",
  "Fuhua Sec",
  "Gan Eng Seng Sch",
  "Geylang Methodist Sec",
  "Greendale Sec",
  "Greenridge Sec",
  "Guangyang Sec",
  "Hai Sing Catholic Sch",
  "Hillgrove Sec",
  "Holy Innocents' High",
  "Hougang Sec",
  "Hua Yi Sec",
  "Hwa Chong Institution",
  "Jurong Pioneer JC",
  "Jurong Sec",
  "Jurong West Sec",
  "Jurongville Sec",
  "Juying Sec",
  "Kent Ridge Sec",
  "Kranji Sec",
  "Kuo Chuan Presbyterian Sec",
  "Loyang View Sec",
  "Manjusri Sec",
  "Maris Stella High Sch",
  "Marsiling Sec",
  "Mayflower Sec",
  "Meridian Sec",
  "Methodist Girls' Sec",
  "Montfort Sec",
  "Nan Chiau High Sch",
  "Nan Hua High Sch",
  "Nanyang Girls' High Sch",
  "Nanyang JC",
  "National JC",
  "Naval Base Sec",
  "New Town Sec",
  "Ngee Ann Sec",
  "North Vista Sec",
  "Northbrooks Sec",
  "Northland Sec",
  "NUS High Sch",
  "Orchid Park Sec",
  "Outram Sec",
  "Pasir Ris Crest Sec",
  "Pasir Ris Sec",
  "Paya Lebar Methodist Girls' Sec",
  "Pei Hwa Sec",
  "Peicai Sec",
  "Peirce Sec",
  "Presbyterian High Sch",
  "Punggol Sec",
  "Queenstown Sec",
  "Queensway Sec",
  "Raffles Girls' Sch",
  "Raffles Institution",
  "Regent Sec",
  "River Valley High Sch",
  "Riverside Sec",
  "St. Andrew's JC",
  "St. Andrew's Sec",
  "St. Anthony's Canossian Sec",
  "St. Gabriel's Sec",
  "St. Hilda's Sec",
  "St. Joseph's Institution",
  "St. Margaret's Sec",
  "St. Patrick's Sch",
  "Sch of the Arts",
  "Sembawang Sec",
  "Sengkang Sec",
  "Serangoon Garden Sec",
  "Serangoon Sec",
  "Singapore Chinese Girls' Sch",
  "Singapore Sports Sch",
  "Springfield Sec",
  "SST, Singapore",
  "Swiss Cottage Sec",
  "Tampines Meridian JC",
  "Tampines Sec",
  "Tanjong Katong Girls'",
  "Tanjong Katong Sec",
  "Temasek JC",
  "Temasek Sec",
  "Unity Sec",
  "Victoria JC",
  "Victoria Sec",
  "West Spring Sec",
  "Westwood Sec",
  "Whitley Sec",
  "Woodgrove Sec",
  "Woodlands Ring Sec",
  "Woodlands Sec",
  "Xinmin Sec",
  "Yio Chu Kang Sec",
  "Yishun Innova JC",
  "Yishun Sec",
  "Yishun Town Sec",
  "Yuan Ching Sec",
  "Yuhua Sec",
  "Yusof Ishak Sec",
  "Yuying Sec",
  "Zhenghua Sec",
  "Zhonghua Sec"
];

export const levels = [

  "Sec 1",
  "Sec 2",
  "Sec 3",
  "Sec 4",
  "Sec 5",

  "J1",
  "J2",
  "J3",

  "Year 1",
  "Year 2",
  "Year 3",
  "Year 4",
  "Year 5",
  "Year 6",

]
