export const schools = [
    "Anderson Serangoon JC",
    "Anglo-Chinese JC",
    "Catholic JC",
    "Dunman High School",
    "Eunoia JC",
    "Hwa Chong Institution",
    "Jurong Pioneer JC",
    "Millennia Institute",
    "Nanyang JC",
    "National JC",
    "Raffles Institution",
    "River Valley High School",
    "St. Andrew's JC",
    "St. Joseph's Institution",
    "Tampines Meridian JC",
    "Temasek JC",
    "Victoria JC",
    "Yishun Innova JC",
    "CHIJ Katong Convent",
    "CHIJ Secondary (Toa Payoh)",
    "CHIJ St. Joseph's Convent",
    "CHIJ St. Nicholas Girls' School",
    "CHIJ St. Theresa's Convent",
    "Chua Chu Kang Secondary School",
    "Christ Church Secondary School",
    "Chung Cheng High School (Main)",
    "Chung Cheng High School (Yishun)",
    "Clementi Town Secondary School",
    "Commonwealth Secondary School",
    "Compassvale Secondary School",
    "Crescent Girls' School",
    "Damai Secondary School",
    "Deyi Secondary School",
    "Dunearn Secondary School",
    "Dunman Secondary School",
    "East Spring Secondary School",
  ]
  
  export const levels = [

    "Sec 1",
    "Sec 2",
    "Sec 3",
    "Sec 4",
    "Sec 5",

    "J1",
    "J2",
    "J3",

    "Year 1",
    "Year 2",
    "Year 3",
    "Year 4",
    "Year 5",
    "Year 6",

  ]