export const schools = [
    "Anderson Serangoon Junior College",
    "Anglo-Chinese Junior College",
    "Catholic Junior College",
    "Dunman High School (Junior College)",
    "Eunoia Junior College",
    "Hwa Chong Institution (Junior College)",
    "Jurong Pioneer Junior College",
    "Millennia Institute",
    "Nanyang Junior College",
    "National Junior College",
    "Raffles Institution (Junior College)",
    "River Valley High School (Junior College)",
    "St. Andrew's Junior College",
    "St. Joseph's Institution (Junior College)",
    "Tampines Meridian Junior College",
    "Temasek Junior College",
    "Victoria Junior College",
    "Yishun Innova Junior College",
    "CHIJ Katong Convent",
    "CHIJ Secondary (Toa Payoh)",
    "CHIJ St. Joseph's Convent",
    "CHIJ St. Nicholas Girls' School",
    "CHIJ St. Theresa's Convent",
    "Chua Chu Kang Secondary School",
    "Christ Church Secondary School",
    "Chung Cheng High School (Main)",
    "Chung Cheng High School (Yishun)",
    "Clementi Town Secondary School",
    "Commonwealth Secondary School",
    "Compassvale Secondary School",
    "Crescent Girls' School",
    "Damai Secondary School",
    "Deyi Secondary School",
    "Dunearn Secondary School",
    "Dunman Secondary School",
    "East Spring Secondary School",
  ]
  
  export const levels = [

    "Sec 1",
    "Sec 2",
    "Sec 3",
    "Sec 4",
    "Sec 5",

    "J1",
    "J2",
    "J3",

    "Year 1",
    "Year 2",
    "Year 3",
    "Year 4",
    "Year 5",
    "Year 6",

  ]